serviceName: track-my-case-dev
namespace: track-my-case-dev

servicePort: http

monitoring:
  interval: 15s

metrics:
  enabled: true
  actuator_endpoint: prometheus
  grafana_dashboard:
    enabled: true
    name: Track My Case UI