const getCourtUrl = (courtText: string): string => {
  if (courtText) {
    if (courtsMap.has(courtText)) {
      return courtsMap.get(courtText)
    }
    if (courtsNameMapping.has(courtText)) {
      const courtNewText = courtsNameMapping.get(courtText)
      if (courtsMap.has(courtNewText)) {
        return courtsMap.get(courtNewText)
      }
    }
  }
  // eslint-disable-next-line no-console
  console.error(`Court not found: [${courtText}]`)
  return null
}

const courtsNameMapping: ReadonlyMap<string, string> = new Map<string, string>([
  // just different spelling
  ["Barkingside  Magistrates' Court", "Barkingside Magistrates' Court"],
  ["Berwick-upon-Tweed Magistrates' Court", "Berwick upon Tweed Magistrates' Court"],
  ["Cardiff  Magistrates' Court", "Cardiff Magistrates' Court"],
  ['Gloucester and Cheltenham County  and Family Court', 'Gloucester and Cheltenham County and Family Court'],
  ['Wrexham County and Family  Court', 'Wrexham County and Family Court'],
  ["Berwick-upon-Tweed Magistrates' Court", "Berwick upon Tweed Magistrates' Court"],
  ["Herefordshire Magistrates' Court", 'Hereford Justice Centre'],
  ['Minshull Street Manchester Crown Court', 'Manchester Crown Court (Minshull St)'],
  ["Southend-on-Sea Magistrates' Court", "Southend Magistrates' Court"],
  ['St. Albans Crown Court', 'St Albans Crown Court'],
  ["St. Albans Magistrates' Court", "St Albans Magistrates' Court"],
  ["Workington Magistrates' Court", 'West Cumbria Courthouse'],
  ["Wycombe Magistrates' Court", "High Wycombe Magistrates' Court and Family Court"],
  ['Bennett House - Stoke CTSC', 'Stoke-on-Trent Combined Court'],

  // court matched by city name
  ["Aberystwyth Magistrates' Court", 'Aberystwyth Justice Centre'],
  ["Aldershot Magistrates' Court", 'Aldershot Justice Centre'],
  ["Amersham Magistrates' Court", 'Amersham Law Courts'],
  ["Barnsley Magistrates' Court", 'Barnsley Law Courts'],
  ["Barnstaple Magistrates' Court", "Barnstaple Magistrates', County and Family Court"],
  ["Bath Magistrates' Court", 'Bath Law Courts (Civil, Family and Magistrates)'],
  ["Bedford Magistrates' Court", 'Bedford County Court and Family Court'],
  ["Beverley Magistrates' Court", "Beverley Magistrates' Court and Hearing Centre"],
  ["Bodmin Magistrates' Court", 'Bodmin Law Courts'],
  ["Bridlington Magistrates' Court", "Bridlington Magistrates' Court and Hearing Centre"],
  ['Caernarfon Crown Court', 'Caernarfon Justice Centre'],
  ["Caernarfon Magistrates' Court", 'Caernarfon Justice Centre'],
  ["Chesterfield Magistrates' Court", 'Chesterfield Justice Centre'],
  ["Colchester Magistrates' Court", "Colchester Magistrates' Court and Family Court"],
  ['Exeter Crown Court', 'Exeter Law Courts'],
  ["Exeter Magistrates' Court", 'Exeter Law Courts'],
  ["Grimsby Magistrates' Court", "Grimsby Magistrates' Court and Family Court"],
  ["Harrogate Magistrates' Court", 'Harrogate Justice Centre'],
  ["Huddersfield Magistrates' Court", 'Huddersfield County Court and Family Court'],
  ["Hull Magistrates' Court", "Hull and Holderness Magistrates' Court and Hearing Centre"],
  ["Huntingdon Magistrates' Court", 'Huntingdon Law Courts'],
  ['Kingston-upon-Hull Crown Court', 'Kingston-upon-Hull Combined Court Centre'],
  ['Lewes Crown Court', 'Lewes Combined Court Centre'],
  ["Llanelli Magistrates' Court", 'Llanelli Law Courts'],
  ["Loughborough Magistrates' Court", 'Loughborough Court'],
  ["Mansfield Magistrates' Court", "Mansfield Magistrates' and County Court"],
  ['Merthyr Tydfil Crown Court', 'Merthyr Tydfil Combined Court Centre'],
  ["Merthyr Tydfil Magistrates' Court", 'Merthyr Tydfil Combined Court Centre'],
  ['Mold Crown Court', 'Mold Justice Centre'],
  ["Mold Magistrates' Court", 'Mold Justice Centre'],
  ['Salisbury Crown Court', 'Salisbury Law Courts'],
  ["Salisbury Magistrates' Court", 'Salisbury Law Courts'],
  ["Scarborough Magistrates' Court", 'Scarborough Justice Centre'],
  ["Sevenoaks Magistrates' Court", "Sevenoaks Magistrates' Court and Family Court"],
  ["Slough Magistrates' Court", 'Slough County Court and Family Court'],
  ['Stoke-on-Trent Crown Court', 'Stoke-on-Trent Combined Court'],
  ["Sunderland Magistrates' Court", 'Sunderland County, Family, Magistrates’ and Tribunal Hearings'],
  ['Warwick Crown Court sitting at Leamington Spa', 'Warwick Combined Court'],
  ["Weymouth Magistrates' Court", 'Weymouth Combined Court'],
  ["Yeovil Magistrates' Court", "Yeovil County, Family and Magistrates' Court"],
  ["North Shields Magistrates' Court", 'North Shields County Court and Family Court'],
  ['Warrington Combined Court', "Warrington Magistrates' Court"],

  // courts with multiple matches, manual selection
  ['Basildon Crown Court', 'Basildon Combined Court'],
  ["Basildon Magistrates' Court", "Basildon Magistrates' Court and Family Court"],
  ['Bolton Combined Court Centre', 'Bolton Crown Court'],
  ['Bradford Crown Court', 'Bradford Combined Court Centre'],
  ["Bradford Magistrates' Court", "Bradford and Keighley Magistrates' Court and Family Court"],
  ["Bristol Magistrates' Court", "Bristol Magistrates' Court and Tribunals Hearing Centre"],
  ['Burnley Crown Court', 'Burnley Combined Court Centre'],
  ['Canterbury Crown Court', 'Canterbury Combined Court Centre'],
  ['Carlisle Crown Court', 'Carlisle Combined Court'],
  ["Chelmsford Magistrates' Court", "Chelmsford Magistrates' Court and Family Court"],
  ['Coventry Crown Court', 'Coventry Combined Court Centre'],
  ["Crewe Magistrates' Court", "Crewe (South Cheshire) Magistrates' Court"],
  ['Derby Crown Court', 'Derby Combined Court Centre'],
  ['Derby Justice Centre (aka Derby St Mary Adult)', "Derby Magistrates' Court"],
  ["Doncaster Magistrates' Court", 'Doncaster Justice Centre South'],
  ["Gateshead Magistrates' Court", "Gateshead Magistrates' Court and Family Court"],
  ['Great Grimsby Crown Court', 'Great Grimsby Combined Court Centre'],
  ["Great Yarmouth Magistrates' Court", "Great Yarmouth Magistrates' Court and Family Court"],
  ["Guildford Magistrates' Court", "Guildford Magistrates' Court and Family Court"],
  ["Isle of Wight Magistrates' Court", 'Isle of Wight Combined Court'],
  ["King's Lynn Magistrates' Court", "King's Lynn Magistrates' Court and Family Court"],
  ["Lancaster Magistrates' Court", 'Lancaster Courthouse'],
  ['Leeds Crown Court', 'Leeds Combined Court Centre'],
  ["Leeds Magistrates' Court", "Leeds District Magistrates' Court and Family Court"],
  ["Liverpool Magistrates' Court", "Liverpool & Knowsley Magistrates' Court"],
  ["Luton Magistrates' Court", "Luton and South Bedfordshire Magistrates' Court"],
  ['Maidstone Crown Court', 'Maidstone Combined Court Centre'],
  ["Manchester City Magistrates' Court", "Manchester Magistrates' Court"],
  ['Manchester Crown Court', 'Manchester Crown Court (Crown Square)'],
  ['Minshull Street Manchester Crown Court', 'Manchester Crown Court (Minshull St)'],
  ["Medway Magistrates' Court", 'Medway (Chatham) Magistrates Court and Family Court'],
  ["Milton Keynes Magistrates' Court", "Milton Keynes Magistrates' Court and Family Court"],
  ["Newcastle Magistrates' Court", "Newcastle upon Tyne Crown Court and Magistrates' Court"],
  ['Newcastle upon Tyne Crown Court', "Newcastle upon Tyne Crown Court and Magistrates' Court"],
  ['Newport (I.O.W.) Crown Court', 'Isle of Wight Combined Court'],
  ["Newport Magistrates' Court", "Newport (South Wales) Magistrates' Court"],
  ["Newport Magistrates' Court (Crown Court Bldg)", 'Newport (South Wales) Crown Court'],
  ['Northampton Crown Court', 'Northampton Crown, County and Family Court'],
  ['Norwich Crown Court', 'Norwich Combined Court Centre'],
  ["Norwich Magistrates' Court", "Norwich Magistrates' Court and Family Court"],
  ['Oxford Crown Court', 'Oxford Combined Court Centre'],
  ["Oxford Magistrates' Court", 'Oxford Magistrates Court'],
  ['Peterborough Crown Court', 'Peterborough Combined Court Centre'],
  ['Plymouth Crown Court', 'Plymouth Combined Court'],
  ['Portsmouth Crown Court', 'Portsmouth Combined Court Centre'],
  ['Preston Crown Court', 'Preston Combined Court Centre'],
  ["Reading Magistrates' Court", "Reading Magistrates' Court and Family Court"],
  ["Romford Magistrates' Court", "Romford Magistrates' Court (formerly Havering Magistrates' Court)"],
  ['Sheffield Crown Court', 'Sheffield Combined Court Centre'],
  ["South East Northumberland Magistrates' Court (aka Bedlington MC)", 'Mid and South East Northumberland Law Courts'],
  ["South Shields Magistrates' Court", "South Tyneside Magistrates' Court"],
  ['Southampton Crown Court', 'Southampton Combined Court Centre'],
  ["Southampton Magistrates' Court", "Southampton (West Hampshire) Magistrates' Court"],
  ['Stafford Crown Court', 'Stafford Combined Court Centre'],
  ["Staines Magistrates' Court", "Staines Magistrates' Court and Family Court"],
  ['Swindon Crown Court', 'Swindon Combined Court'],
  ['Taunton Crown Court', 'Taunton Crown, County and Family Court'],
  ["Taunton Magistrates' Court", "Taunton Magistrates' Court, Tribunals and Family Hearing Centre"],
  ['Teesside Crown Court', 'Teesside Combined Court Centre'],
  ['Truro Crown Court', 'Truro Combined Court'],
  ["Wigan Magistrates' Court", "Wigan and Leigh Magistrates' Court"],
  ['Winchester Crown Court', 'Winchester Combined Court Centre'],
  ['Wolverhampton Crown Court', 'Wolverhampton Combined Court Centre'],
  ['Worcester Crown Court', 'Worcester Combined Court'],
  ["Worcester Magistrates' Court", 'Worcester Justice Centre'],
  ["York Magistrates' Court", "York Magistrates' Court and Family Court"],
])

const allCourts: ReadonlySet<string> = new Set([
  "Aberystwyth Magistrates' Court",
  "Aldershot Magistrates' Court",
  "Amersham Magistrates' Court",
  'Aylesbury Crown Court',
  "Banbury Magistrates' Court",
  "Barkingside Magistrates' Court",
  "Barnsley Magistrates' Court",
  "Barnstaple Magistrates' Court",
  "Barrow-in-Furness Magistrates' Court",
  'Basildon Crown Court',
  "Basildon Magistrates' Court",
  "Basingstoke Magistrates' Court",
  "Bath Magistrates' Court",
  "Bedford Magistrates' Court",
  'Bennett House - Stoke CTSC',
  "Berwick-upon-Tweed Magistrates' Court",
  "Beverley Magistrates' Court",
  "Bexley Magistrates' Court",
  'Birmingham Crown Court',
  "Birmingham Magistrates' Court",
  "Blackburn Magistrates' Court",
  'Blackfriars Crown Court',
  "Blackpool Magistrates' Court",
  "Bodmin Magistrates' Court",
  'Bolton Combined Court Centre',
  'Bolton Crown Court',
  "Boston Magistrates' Court",
  'Bournemouth Crown Court',
  'Bradford Crown Court',
  "Bradford Magistrates' Court",
  "Bridlington Magistrates' Court",
  "Brighton Magistrates' Court",
  'Bristol Crown Court',
  "Bristol Magistrates' Court",
  "Bromley Magistrates' Court",
  'Burnley Crown Court',
  "Burnley Magistrates' Court",
  'Caernarfon Crown Court',
  "Caernarfon Magistrates' Court",
  'Cambridge Crown Court',
  "Cambridge Magistrates' Court",
  "Cannock Magistrates' Court",
  'Canterbury Crown Court',
  "Canterbury Magistrates' Court",
  'Cardiff Crown Court',
  "Cardiff Magistrates' Court",
  'Carlisle Crown Court',
  "Carlisle Magistrates' Court",
  'Central Criminal Court',
  'Chelmsford Crown Court',
  "Chelmsford Magistrates' Court",
  "Cheltenham Magistrates' Court",
  'Chester Crown Court',
  "Chester Magistrates' Court",
  "Chesterfield Magistrates' Court",
  "City of London Magistrates' Court",
  "Colchester Magistrates' Court",
  'Coventry Crown Court',
  "Coventry Magistrates' Court",
  "Crawley Magistrates' Court",
  "Crewe Magistrates' Court",
  'Croydon Crown Court',
  "Croydon Magistrates' Court",
  "Cwmbran Magistrates' Court",
  'Derby Crown Court',
  'Derby Justice Centre (aka Derby St Mary Adult)',
  "Doncaster Magistrates' Court",
  "Dudley Magistrates' Court",
  'Durham Crown Court',
  "Ealing Magistrates' Court",
  'Exeter Crown Court',
  "Exeter Magistrates' Court",
  "Folkestone Magistrates' Court",
  "Gateshead Magistrates' Court",
  'Gloucester Crown Court',
  'Great Grimsby Crown Court',
  "Great Yarmouth Magistrates' Court",
  "Grimsby Magistrates' Court",
  'Guildford Crown Court',
  "Guildford Magistrates' Court",
  "Harrogate Magistrates' Court",
  'Harrow Crown Court',
  "Hastings Magistrates' Court",
  "Hatfield Magistrates' Court",
  "Haverfordwest Magistrates' Court",
  "Hendon Magistrates' Court",
  "Herefordshire Magistrates' Court",
  "Highbury Corner Magistrates' Court",
  "Horsham Magistrates' Court",
  "Huddersfield Magistrates' Court",
  "Hull Magistrates' Court",
  "Huntingdon Magistrates' Court",
  'Inner London Crown Court',
  'Ipswich Crown Court',
  "Ipswich Magistrates' Court",
  "Isle of Wight Magistrates' Court",
  'Isleworth Crown Court',
  "Kidderminster Magistrates' Court",
  "King's Lynn Magistrates' Court",
  'Kingston upon Thames Crown Court',
  'Kingston-upon-Hull Crown Court',
  'Lancaster Crown Court',
  "Lancaster Magistrates' Court",
  "Lavender Hill Magistrates' Court",
  "Leamington Spa Magistrates' Court",
  'Leeds Crown Court',
  "Leeds Magistrates' Court",
  'Leicester Crown Court',
  "Leicester Magistrates' Court",
  'Lewes Crown Court',
  'Lincoln Crown Court',
  "Lincoln Magistrates' Court",
  'Liverpool Crown Court',
  "Liverpool Magistrates' Court",
  "Llandrindod Wells Magistrates' and Family Court",
  "Llandudno Magistrates' Court",
  "Llanelli Magistrates' Court",
  "Loughborough Magistrates' Court",
  'Luton Crown Court',
  "Luton Magistrates' Court",
  'Maidenhead Courthouse',
  'Maidstone Crown Court',
  "Maidstone Magistrates' Court",
  "Manchester City Magistrates' Court",
  'Manchester Crown Court',
  "Mansfield Magistrates' Court",
  "Margate Magistrates' Court",
  "Medway Magistrates' Court",
  'Merthyr Tydfil Crown Court',
  "Merthyr Tydfil Magistrates' Court",
  "Milton Keynes Magistrates' Court",
  'Minshull Street Manchester Crown Court',
  'Mold Crown Court',
  "Mold Magistrates' Court",
  "Newcastle Magistrates' Court",
  'Newcastle upon Tyne Crown Court',
  'Newport (I.O.W.) Crown Court',
  "Newport Magistrates' Court",
  "Newport Magistrates' Court (Crown Court Bldg)",
  "Newton Abbot Magistrates' Court",
  "Newton Aycliffe Magistrates' Court",
  "North Shields Magistrates' Court",
  "North Somerset Magistrates' Court",
  'North Staffordshire Justice Centre',
  'Northampton Crown Court',
  "Northampton Magistrates' Court",
  'Norwich Crown Court',
  "Norwich Magistrates' Court",
  'Nottingham Crown Court',
  "Nottingham Magistrates' Court",
  "Nuneaton Magistrates' Court",
  'Oxford Crown Court',
  "Oxford Magistrates' Court",
  'Peterborough Crown Court',
  "Peterborough Magistrates' Court",
  "Peterlee Magistrates' Court",
  'Plymouth Crown Court',
  "Plymouth Magistrates' Court",
  "Poole Magistrates' Court",
  'Portsmouth Crown Court',
  "Portsmouth Magistrates' Court",
  'Preston Crown Court',
  "Preston Magistrates' Court",
  'Reading Crown Court',
  "Reading Magistrates' Court",
  "Redditch Magistrates' Court",
  "Romford Magistrates' Court",
  'Salisbury Crown Court',
  "Salisbury Magistrates' Court",
  "Scarborough Magistrates' Court",
  "Sefton Magistrates' Court",
  "Sevenoaks Magistrates' Court",
  'Sheffield Crown Court',
  "Sheffield Magistrates' Court",
  'Shrewsbury Crown Court',
  "Skipton Magistrates' Court",
  "Slough Magistrates' Court",
  'Snaresbrook Crown Court',
  "South East Northumberland Magistrates' Court (aka Bedlington MC)",
  "South Shields Magistrates' Court",
  'Southampton Crown Court',
  "Southampton Magistrates' Court",
  "Southend-on-Sea Magistrates' Court",
  'Southwark Crown Court',
  'St. Albans Crown Court',
  "St. Albans Magistrates' Court",
  'Stafford Crown Court',
  "Staines Magistrates' Court",
  "Stevenage Magistrates' Court",
  "Stockport Magistrates' Court",
  'Stoke-on-Trent Crown Court',
  "Stratford Magistrates' Court",
  "Sunderland Magistrates' Court",
  'Swansea Crown Court',
  "Swansea Magistrates' Court",
  'Swindon Crown Court',
  "Swindon Magistrates' Court",
  "Tameside Magistrates' Court",
  'Taunton Crown Court',
  "Taunton Magistrates' Court",
  'Teesside Crown Court',
  "Teesside Magistrates' Court",
  "Telford Magistrates' Court",
  "Thames Magistrates' Court",
  'Truro Crown Court',
  "Truro Magistrates' Court",
  "Uxbridge Magistrates' Court",
  "Walsall Magistrates' Court",
  'Warrington Combined Court',
  'Warrington Crown Court',
  'Warwick Crown Court sitting at Leamington Spa',
  "Wellingborough Magistrates' Court",
  "Welshpool Magistrates' Court",
  "Westminster Magistrates' Court",
  "Weymouth Magistrates' Court",
  "Wigan Magistrates' Court",
  "Willesden Magistrates' Court",
  "Wimbledon Magistrates' Court",
  'Winchester Crown Court',
  "Wirral Magistrates' Court",
  'Wolverhampton Crown Court',
  "Wolverhampton Magistrates' Court",
  'Wood Green Crown Court',
  'Woolwich Crown Court',
  'Worcester Crown Court',
  "Worcester Magistrates' Court",
  "Workington Magistrates' Court",
  "Worthing Magistrates' Court",
  "Wrexham Magistrates' Court",
  "Wycombe Magistrates' Court",
  "Yeovil Magistrates' Court",
  'York Crown Court',
  "York Magistrates' Court",
])

const courtsMap: ReadonlyMap<string, string> = new Map<string, string>([
  ['Administrative Court', 'https://www.find-court-tribunal.service.gov.uk/courts/administrative-court'],
  [
    'Admiralty and Commercial Court',
    'https://www.find-court-tribunal.service.gov.uk/courts/admiralty-and-commercial-court',
  ],
  ['Aldershot Justice Centre', 'https://www.find-court-tribunal.service.gov.uk/courts/aldershot-justice-centre'],
  ['Amersham Law Courts', 'https://www.find-court-tribunal.service.gov.uk/courts/amersham-law-courts'],
  [
    'Ashford Tribunal Hearing Centre',
    'https://www.find-court-tribunal.service.gov.uk/courts/ashford-tribunal-hearing-centre',
  ],
  [
    'Avon and Somerset Enforcement Department',
    'https://www.find-court-tribunal.service.gov.uk/courts/avon-and-somerset-enforcement-department',
  ],
  ['Aylesbury Crown Court', 'https://www.find-court-tribunal.service.gov.uk/courts/aylesbury-crown-court'],
  [
    'Bankruptcy Court (High Court)',
    'https://www.find-court-tribunal.service.gov.uk/courts/bankruptcy-court-high-court',
  ],
  [
    "Barkingside Magistrates' Court",
    'https://www.find-court-tribunal.service.gov.uk/courts/barkingside--magistrates-court',
  ],
  [
    'Barnet Civil and Family Courts Centre',
    'https://www.find-court-tribunal.service.gov.uk/courts/barnet-civil-and-family-courts-centre',
  ],
  ['Barnsley Law Courts', 'https://www.find-court-tribunal.service.gov.uk/courts/barnsley-law-courts'],
  [
    "Barnstaple Magistrates', County and Family Court",
    'https://www.find-court-tribunal.service.gov.uk/courts/barnstaple-magistrates-county-and-family-court',
  ],
  [
    'Barrow-in-Furness County Court and Family Court',
    'https://www.find-court-tribunal.service.gov.uk/courts/barrow-in-furness-county-court-and-family-court',
  ],
  [
    "Barrow-in-Furness Magistrates' Court",
    'https://www.find-court-tribunal.service.gov.uk/courts/barrow-in-furness-magistrates-court',
  ],
  ['Basildon Combined Court', 'https://www.find-court-tribunal.service.gov.uk/courts/basildon-combined-court'],
  [
    "Basildon Magistrates' Court and Family Court",
    'https://www.find-court-tribunal.service.gov.uk/courts/basildon-magistrates-court-and-family-court',
  ],
  [
    'Basingstoke County Court and Family Court',
    'https://www.find-court-tribunal.service.gov.uk/courts/basingstoke-county-court-and-family-court',
  ],
  [
    "Basingstoke Magistrates' Court",
    'https://www.find-court-tribunal.service.gov.uk/courts/basingstoke-magistrates-court',
  ],
  [
    'Bath Law Courts (Civil, Family and Magistrates)',
    'https://www.find-court-tribunal.service.gov.uk/courts/bath-law-courts-civil-family-and-magistrates',
  ],
  [
    'Bedford County Court and Family Court',
    'https://www.find-court-tribunal.service.gov.uk/courts/bedford-county-court-and-family-court',
  ],
  ["Belmarsh Magistrates' Court", 'https://www.find-court-tribunal.service.gov.uk/courts/belmarsh-magistrates-court'],
  [
    "Berwick upon Tweed Magistrates' Court",
    'https://www.find-court-tribunal.service.gov.uk/courts/berwick-upon-tweed-magistrates-court',
  ],
  [
    "Beverley Magistrates' Court and Hearing Centre",
    'https://www.find-court-tribunal.service.gov.uk/courts/beverley-magistrates-court-and-hearing-centre',
  ],
  ["Bexley Magistrates' Court", 'https://www.find-court-tribunal.service.gov.uk/courts/bexley-magistrates-court'],
  ['Birkenhead County Court', 'https://www.find-court-tribunal.service.gov.uk/courts/birkenhead-county-court'],
  [
    'Birmingham Civil and Family Justice Centre',
    'https://www.find-court-tribunal.service.gov.uk/courts/birmingham-civil-and-family-justice-centre',
  ],
  ['Birmingham Crown Court', 'https://www.find-court-tribunal.service.gov.uk/courts/birmingham-crown-court'],
  [
    'Birmingham Immigration and Asylum Chamber (First Tier Tribunal)',
    'https://www.find-court-tribunal.service.gov.uk/courts/birmingham-immigration-and-asylum-chamber-first-tier-tribunal',
  ],
  [
    "Birmingham Magistrates' Court",
    'https://www.find-court-tribunal.service.gov.uk/courts/birmingham-magistrates-court',
  ],
  ['Birmingham Youth Court', 'https://www.find-court-tribunal.service.gov.uk/courts/birmingham-youth-court'],
  ['Blackburn Family Court', 'https://www.find-court-tribunal.service.gov.uk/courts/blackburn-family-court'],
  ["Blackburn Magistrates' Court", 'https://www.find-court-tribunal.service.gov.uk/courts/blackburn-magistrates-court'],
  [
    'Blackpool Family and Civil Court',
    'https://www.find-court-tribunal.service.gov.uk/courts/blackpool-family-and-civil-court',
  ],
  ["Blackpool Magistrates' Court", 'https://www.find-court-tribunal.service.gov.uk/courts/blackpool-magistrates-court'],
  [
    'Blackwood Civil and Family Court',
    'https://www.find-court-tribunal.service.gov.uk/courts/blackwood-civil-and-family-court',
  ],
  ['Bodmin Law Courts', 'https://www.find-court-tribunal.service.gov.uk/courts/bodmin-county-court-and-family-court'],
  ['Bolton Crown Court', 'https://www.find-court-tribunal.service.gov.uk/courts/bolton-crown-court'],
  ["Bolton Magistrates' Court", 'https://www.find-court-tribunal.service.gov.uk/courts/bolton-magistrates-court'],
  [
    'Boston County Court and Family Court',
    'https://www.find-court-tribunal.service.gov.uk/courts/boston-county-court-and-family-court',
  ],
  ["Boston Magistrates' Court", 'https://www.find-court-tribunal.service.gov.uk/courts/boston-magistrates-court'],
  [
    'Bournemouth Combined Court',
    'https://www.find-court-tribunal.service.gov.uk/courts/bournemouth-and-poole-county-court-and-family-court',
  ],
  ['Bournemouth Crown Court', 'https://www.find-court-tribunal.service.gov.uk/courts/bournemouth-crown-court'],
  [
    "Bradford and Keighley Magistrates' Court and Family Court",
    'https://www.find-court-tribunal.service.gov.uk/courts/bradford-and-keighley-magistrates-court-and-family-court',
  ],
  [
    'Bradford Combined Court Centre',
    'https://www.find-court-tribunal.service.gov.uk/courts/bradford-combined-court-centre',
  ],
  [
    'Brentford County and Family Court',
    'https://www.find-court-tribunal.service.gov.uk/courts/brentford-county-and-family-court',
  ],
  [
    "Bridlington Magistrates' Court and Hearing Centre",
    'https://www.find-court-tribunal.service.gov.uk/courts/bridlington-magistrates-court-and-hearing-centre',
  ],
  ['Brighton County Court', 'https://www.find-court-tribunal.service.gov.uk/courts/brighton-county-court'],
  ["Brighton Magistrates' Court", 'https://www.find-court-tribunal.service.gov.uk/courts/brighton-magistrates-court'],
  ['Bristol Crown Court', 'https://www.find-court-tribunal.service.gov.uk/courts/bristol-crown-court'],
  [
    "Bristol Magistrates' Court and Tribunals Hearing Centre",
    'https://www.find-court-tribunal.service.gov.uk/courts/bristol-magistrates-court-and-tribunals-hearing-centre',
  ],
  [
    'Bromley County Court and Family Court',
    'https://www.find-court-tribunal.service.gov.uk/courts/bromley-county-court-and-family-court',
  ],
  ["Bromley Magistrates' Court", 'https://www.find-court-tribunal.service.gov.uk/courts/bromley-magistrates-court'],
  [
    'Burnley Combined Court Centre',
    'https://www.find-court-tribunal.service.gov.uk/courts/burnley-combined-court-centre',
  ],
  ["Burnley Magistrates' Court", 'https://www.find-court-tribunal.service.gov.uk/courts/burnley-magistrates-court'],
  [
    'Bury St Edmunds County Court and Family Court',
    'https://www.find-court-tribunal.service.gov.uk/courts/bury-st-edmunds-county-court-and-family-court',
  ],
  [
    'Cambridge County Court and Family Court',
    'https://www.find-court-tribunal.service.gov.uk/courts/cambridge-county-court-and-family-court',
  ],
  ['Cambridge Crown Court', 'https://www.find-court-tribunal.service.gov.uk/courts/cambridge-crown-court'],
  ["Cambridge Magistrates' Court", 'https://www.find-court-tribunal.service.gov.uk/courts/cambridge-magistrates-court'],
  ["Cannock Magistrates' Court", 'https://www.find-court-tribunal.service.gov.uk/courts/cannock-magistrates-court'],
  [
    'Canterbury Combined Court Centre',
    'https://www.find-court-tribunal.service.gov.uk/courts/canterbury-combined-court-centre',
  ],
  [
    "Canterbury Magistrates' Court",
    'https://www.find-court-tribunal.service.gov.uk/courts/canterbury-magistrates-court',
  ],
  ["Cardiff Magistrates' Court", 'https://www.find-court-tribunal.service.gov.uk/courts/cardiff--magistrates-court'],
  ['Cardiff Crown Court', 'https://www.find-court-tribunal.service.gov.uk/courts/cardiff-crown-court'],
  [
    'Cardiff Probate Registry of Wales',
    'https://www.find-court-tribunal.service.gov.uk/courts/cardiff-probate-registry-of-wales',
  ],
  ['Carlisle Combined Court', 'https://www.find-court-tribunal.service.gov.uk/courts/carlisle-combined-court'],
  ["Carlisle Magistrates' Court", 'https://www.find-court-tribunal.service.gov.uk/courts/carlisle-magistrates-court'],
  [
    'Carmarthen County Court and Family Court',
    'https://www.find-court-tribunal.service.gov.uk/courts/carmarthen-county-court-and-family-court',
  ],
  ['Central Criminal Court', 'https://www.find-court-tribunal.service.gov.uk/courts/central-criminal-court'],
  ['Central Family Court', 'https://www.find-court-tribunal.service.gov.uk/courts/central-family-court'],
  [
    'Central London County Court (Bankruptcy)',
    'https://www.find-court-tribunal.service.gov.uk/courts/central-london-county-court-bankruptcy',
  ],
  ['Central London County Court', 'https://www.find-court-tribunal.service.gov.uk/courts/central-london-county-court'],
  ['Chelmsford Crown Court', 'https://www.find-court-tribunal.service.gov.uk/courts/chelmsford-crown-court'],
  [
    "Chelmsford Magistrates' Court and Family Court",
    'https://www.find-court-tribunal.service.gov.uk/courts/chelmsford-magistrates-court-and-family-court',
  ],
  [
    "Cheltenham Magistrates' Court",
    'https://www.find-court-tribunal.service.gov.uk/courts/cheltenham-magistrates-court',
  ],
  ['Chester Crown Court', 'https://www.find-court-tribunal.service.gov.uk/courts/chester-crown-court'],
  ["Chester Magistrates' Court", 'https://www.find-court-tribunal.service.gov.uk/courts/chester-magistrates-court'],
  [
    'Chichester Nightingale Crown Court',
    'https://www.find-court-tribunal.service.gov.uk/courts/chichester-nightingale-crown-court',
  ],
  [
    "City of London Magistrates' Court",
    'https://www.find-court-tribunal.service.gov.uk/courts/city-of-london-magistrates-court',
  ],
  [
    'Clerkenwell and Shoreditch County Court and Family Court',
    'https://www.find-court-tribunal.service.gov.uk/courts/clerkenwell-and-shoreditch-county-court-and-family-court',
  ],
  [
    "Colchester Magistrates' Court and Family Court",
    'https://www.find-court-tribunal.service.gov.uk/courts/colchester-magistrates-court-and-family-court',
  ],
  [
    'Court of Appeal Civil Division',
    'https://www.find-court-tribunal.service.gov.uk/courts/court-of-appeal-civil-division',
  ],
  [
    'Court of Appeal Criminal Division',
    'https://www.find-court-tribunal.service.gov.uk/courts/court-of-appeal-criminal-division',
  ],
  ['Court of Protection', 'https://www.find-court-tribunal.service.gov.uk/courts/court-of-protection'],
  [
    'Coventry Combined Court Centre',
    'https://www.find-court-tribunal.service.gov.uk/courts/coventry-combined-court-centre',
  ],
  ["Coventry Magistrates' Court", 'https://www.find-court-tribunal.service.gov.uk/courts/coventry-magistrates-court'],
  ["Crawley Magistrates' Court", 'https://www.find-court-tribunal.service.gov.uk/courts/crawley-magistrates-court'],
  [
    "Crewe (South Cheshire) Magistrates' Court",
    'https://www.find-court-tribunal.service.gov.uk/courts/crewe-south-cheshire-magistrates-court',
  ],
  [
    'Crewe County Court and Family Court',
    'https://www.find-court-tribunal.service.gov.uk/courts/crewe-county-court-and-family-court',
  ],
  [
    'Croydon County Court and Family Court',
    'https://www.find-court-tribunal.service.gov.uk/courts/croydon-county-court-and-family-court',
  ],
  ['Croydon Crown Court', 'https://www.find-court-tribunal.service.gov.uk/courts/croydon-crown-court'],
  ['Croydon Employment Tribunal', 'https://www.find-court-tribunal.service.gov.uk/courts/croydon-employment-tribunal'],
  ["Croydon Magistrates' Court", 'https://www.find-court-tribunal.service.gov.uk/courts/croydon-magistrates-court'],
  ["Cwmbran Magistrates' Court", 'https://www.find-court-tribunal.service.gov.uk/courts/cwmbran-magistrates-court'],
  [
    'Darlington County Court and Family Court',
    'https://www.find-court-tribunal.service.gov.uk/courts/darlington-county-court-and-family-court',
  ],
  [
    "Darlington Magistrates' Court and Family Court",
    'https://www.find-court-tribunal.service.gov.uk/courts/darlington-magistrates-court-and-family-court',
  ],
  [
    'Dartford County Court and Family Court',
    'https://www.find-court-tribunal.service.gov.uk/courts/dartford-county-court-and-family-court',
  ],
  ['Derby Combined Court Centre', 'https://www.find-court-tribunal.service.gov.uk/courts/derby-combined-court-centre'],
  ["Derby Magistrates' Court", 'https://www.find-court-tribunal.service.gov.uk/courts/derby-magistrates-court'],
  [
    'Devon and Cornwall Central Finance Unit',
    'https://www.find-court-tribunal.service.gov.uk/courts/devon-and-cornwall-central-finance-unit',
  ],
  [
    'Dudley County Court and Family Court',
    'https://www.find-court-tribunal.service.gov.uk/courts/dudley-county-court-and-family-court',
  ],
  ["Dudley Magistrates' Court", 'https://www.find-court-tribunal.service.gov.uk/courts/dudley-magistrates-court'],
  [
    'Durham County Court and Family Court',
    'https://www.find-court-tribunal.service.gov.uk/courts/durham-county-court-and-family-court',
  ],
  ['Durham Crown Court', 'https://www.find-court-tribunal.service.gov.uk/courts/durham-crown-court'],
  ["Ealing Magistrates' Court", 'https://www.find-court-tribunal.service.gov.uk/courts/ealing-magistrates-court'],
  [
    "East Berkshire Magistrates' Court, Slough",
    'https://www.find-court-tribunal.service.gov.uk/courts/east-berkshire-magistrates-court-slough',
  ],
  ['East London Family Court', 'https://www.find-court-tribunal.service.gov.uk/courts/east-london-family-court'],
  [
    'Edmonton County Court and Family Court',
    'https://www.find-court-tribunal.service.gov.uk/courts/edmonton-county-court-and-family-court',
  ],
  ['Exeter Law Courts', 'https://www.find-court-tribunal.service.gov.uk/courts/exeter-law-courts'],
  ['Family Division', 'https://www.find-court-tribunal.service.gov.uk/courts/family-division'],
  [
    "Folkestone Magistrates' Court",
    'https://www.find-court-tribunal.service.gov.uk/courts/folkestone-magistrates-court',
  ],
  [
    'Gateshead County Court and Family Court',
    'https://www.find-court-tribunal.service.gov.uk/courts/gateshead-county-court-and-family-court',
  ],
  [
    "Gateshead Magistrates' Court and Family Court",
    'https://www.find-court-tribunal.service.gov.uk/courts/gateshead-magistrates-court-and-family-court',
  ],
  [
    'Gloucester and Cheltenham County and Family Court',
    'https://www.find-court-tribunal.service.gov.uk/courts/gloucester-and-cheltenham-county-and-family-court',
  ],
  ['Gloucester Crown Court', 'https://www.find-court-tribunal.service.gov.uk/courts/gloucester-crown-court'],
  [
    'Great Grimsby Combined Court Centre',
    'https://www.find-court-tribunal.service.gov.uk/courts/great-grimsby-combined-court-centre',
  ],
  [
    "Great Yarmouth Magistrates' Court and Family Court",
    'https://www.find-court-tribunal.service.gov.uk/courts/great-yarmouth-magistrates-court-and-family-court',
  ],
  [
    'Greater Manchester Central Accounts and Enforcement Unit',
    'https://www.find-court-tribunal.service.gov.uk/courts/greater-manchester-central-accounts-and-enforcement-unit',
  ],
  [
    "Grimsby Magistrates' Court and Family Court",
    'https://www.find-court-tribunal.service.gov.uk/courts/grimsby-magistrates-court-and-family-court',
  ],
  [
    'Guildford County Court and Family Court',
    'https://www.find-court-tribunal.service.gov.uk/courts/guildford-county-court-and-family-court',
  ],
  ['Guildford Crown Court', 'https://www.find-court-tribunal.service.gov.uk/courts/guildford-crown-court'],
  [
    "Guildford Magistrates' Court and Family Court",
    'https://www.find-court-tribunal.service.gov.uk/courts/guildford-magistrates-court-and-family-court',
  ],
  ['Harrogate Justice Centre', 'https://www.find-court-tribunal.service.gov.uk/courts/harrogate-justice-centre'],
  ['Harrow Crown Court', 'https://www.find-court-tribunal.service.gov.uk/courts/harrow-crown-court'],
  [
    'Hastings County Court and Family Court',
    'https://www.find-court-tribunal.service.gov.uk/courts/hastings-county-court-and-family-court',
  ],
  ["Hastings Magistrates' Court", 'https://www.find-court-tribunal.service.gov.uk/courts/hastings-magistrates-court'],
  ["Hatfield Magistrates' Court", 'https://www.find-court-tribunal.service.gov.uk/courts/hatfield-magistrates-court'],
  ['Havant Justice Centre', 'https://www.find-court-tribunal.service.gov.uk/courts/havant-justice-centre'],
  [
    'Haverfordwest County Court and Family Court',
    'https://www.find-court-tribunal.service.gov.uk/courts/haverfordwest-county-court-and-family-court',
  ],
  [
    "Haverfordwest Magistrates' Court",
    'https://www.find-court-tribunal.service.gov.uk/courts/haverfordwest-magistrates-court',
  ],
  ["Hendon Magistrates' Court", 'https://www.find-court-tribunal.service.gov.uk/courts/hendon-magistrates-court'],
  [
    'Hereford County Court and Family Court',
    'https://www.find-court-tribunal.service.gov.uk/courts/hereford-county-court-and-family-court',
  ],
  ['Hereford Crown Court', 'https://www.find-court-tribunal.service.gov.uk/courts/hereford-crown-court'],
  ['Hereford Justice Centre', 'https://www.find-court-tribunal.service.gov.uk/courts/hereford-justice-centre'],
  [
    'Hertford County Court and Family Court',
    'https://www.find-court-tribunal.service.gov.uk/courts/hertford-county-court-and-family-court',
  ],
  [
    'High Wycombe County Court and Family Court',
    'https://www.find-court-tribunal.service.gov.uk/courts/high-wycombe-county-court-and-family-court',
  ],
  [
    "High Wycombe Magistrates' Court and Family Court",
    'https://www.find-court-tribunal.service.gov.uk/courts/high-wycombe-magistrates-court-and-family-court',
  ],
  [
    "Highbury Corner Magistrates' Court",
    'https://www.find-court-tribunal.service.gov.uk/courts/highbury-corner-magistrates-court',
  ],
  [
    'Horsham County Court and Family Court',
    'https://www.find-court-tribunal.service.gov.uk/courts/horsham-county-court-and-family-court',
  ],
  ["Horsham Magistrates' Court", 'https://www.find-court-tribunal.service.gov.uk/courts/horsham-magistrates-court'],
  ['Hove Trial Centre', 'https://www.find-court-tribunal.service.gov.uk/courts/hove-trial-centre'],
  [
    'Huddersfield County Court and Family Court',
    'https://www.find-court-tribunal.service.gov.uk/courts/huddersfield-county-court-and-family-court',
  ],
  [
    "Hull and Holderness Magistrates' Court and Hearing Centre",
    'https://www.find-court-tribunal.service.gov.uk/courts/hull-and-holderness-magistrates-court-and-hearing-centre',
  ],
  ['Huntingdon Law Courts', 'https://www.find-court-tribunal.service.gov.uk/courts/huntingdon-law-courts'],
  ['Inner London Crown Court', 'https://www.find-court-tribunal.service.gov.uk/courts/inner-london-crown-court'],
  [
    'Ipswich County Court and Family Hearing Centre',
    'https://www.find-court-tribunal.service.gov.uk/courts/ipswich-county-court-and-family-hearing-centre',
  ],
  ['Ipswich Crown Court', 'https://www.find-court-tribunal.service.gov.uk/courts/ipswich-crown-court'],
  ["Ipswich Magistrates' Court", 'https://www.find-court-tribunal.service.gov.uk/courts/ipswich-magistrates-court'],
  [
    'Isle of Wight Combined Court',
    'https://www.find-court-tribunal.service.gov.uk/courts/isle-of-wight-combined-court',
  ],
  ['Isleworth Crown Court', 'https://www.find-court-tribunal.service.gov.uk/courts/isleworth-crown-court'],
  [
    "Kidderminster Magistrates' Court",
    'https://www.find-court-tribunal.service.gov.uk/courts/kidderminster-magistrates-court',
  ],
  ["King's Bench Division", 'https://www.find-court-tribunal.service.gov.uk/courts/kings-bench-division'],
  ["King's Lynn Crown Court", 'https://www.find-court-tribunal.service.gov.uk/courts/kings-lynn-crown-court'],
  [
    "King's Lynn Magistrates' Court and Family Court",
    'https://www.find-court-tribunal.service.gov.uk/courts/kings-lynn-magistrates-court-and-family-court',
  ],
  [
    'Kingston upon Thames County Court and Family Court',
    'https://www.find-court-tribunal.service.gov.uk/courts/kingston-upon-thames-county-court-and-family-court',
  ],
  [
    'Kingston upon Thames Crown Court',
    'https://www.find-court-tribunal.service.gov.uk/courts/kingston-upon-thames-crown-court',
  ],
  [
    'Kingston-upon-Hull Combined Court Centre',
    'https://www.find-court-tribunal.service.gov.uk/courts/kingston-upon-hull-combined-court-centre',
  ],
  [
    "Kirklees (Huddersfield) Magistrates' Court and Family Court",
    'https://www.find-court-tribunal.service.gov.uk/courts/kirklees-huddersfield-magistrates-court-and-family-court',
  ],
  ['Lancaster Courthouse', 'https://www.find-court-tribunal.service.gov.uk/courts/lancaster-courthouse'],
  ['Lancaster Crown Court', 'https://www.find-court-tribunal.service.gov.uk/courts/lancaster-crown-court'],
  [
    "Lavender Hill Magistrates' Court",
    'https://www.find-court-tribunal.service.gov.uk/courts/lavender-hill-magistrates-court',
  ],
  [
    "Leamington Spa Magistrates' Court",
    'https://www.find-court-tribunal.service.gov.uk/courts/leamington-spa-magistrates-court',
  ],
  [
    'Leeds Business Property Court',
    'https://www.find-court-tribunal.service.gov.uk/courts/leeds-business-property-court',
  ],
  ['Leeds Combined Court Centre', 'https://www.find-court-tribunal.service.gov.uk/courts/leeds-combined-court-centre'],
  [
    "Leeds District Magistrates' Court and Family Court",
    'https://www.find-court-tribunal.service.gov.uk/courts/leeds-district-magistrates-court-and-family-court',
  ],
  [
    'Leicester County Court and Family Court',
    'https://www.find-court-tribunal.service.gov.uk/courts/leicester-county-court-and-family-court',
  ],
  ['Leicester Crown Court', 'https://www.find-court-tribunal.service.gov.uk/courts/leicester-crown-court'],
  ["Leicester Magistrates' Court", 'https://www.find-court-tribunal.service.gov.uk/courts/leicester-magistrates-court'],
  [
    'Leicester Tribunal Hearing Centre',
    'https://www.find-court-tribunal.service.gov.uk/courts/leicester-tribunal-hearing-centre',
  ],
  ['Lewes Combined Court Centre', 'https://www.find-court-tribunal.service.gov.uk/courts/lewes-combined-court-centre'],
  [
    'Lincoln County Court and Family Court',
    'https://www.find-court-tribunal.service.gov.uk/courts/lincoln-county-court-and-family-court',
  ],
  ['Lincoln Crown Court', 'https://www.find-court-tribunal.service.gov.uk/courts/lincoln-crown-court'],
  ["Lincoln Magistrates' Court", 'https://www.find-court-tribunal.service.gov.uk/courts/lincoln-magistrates-court'],
  [
    "Liverpool & Knowsley Magistrates' Court",
    'https://www.find-court-tribunal.service.gov.uk/courts/liverpool-knowsley-magistrates-court',
  ],
  [
    'Liverpool Civil and Family Court',
    'https://www.find-court-tribunal.service.gov.uk/courts/liverpool-civil-and-family-court',
  ],
  ['Liverpool Crown Court', 'https://www.find-court-tribunal.service.gov.uk/courts/liverpool-crown-court'],
  [
    'Liverpool District Probate Registry',
    'https://www.find-court-tribunal.service.gov.uk/courts/liverpool-district-probate-registry',
  ],
  ['Liverpool Youth Court', 'https://www.find-court-tribunal.service.gov.uk/courts/liverpool-youth-court'],
  [
    "Llandrindod Wells Magistrates' and Family Court",
    'https://www.find-court-tribunal.service.gov.uk/courts/llandrindod-wells-magistrates-and-family-court',
  ],
  ["Llandudno Magistrates' Court", 'https://www.find-court-tribunal.service.gov.uk/courts/llandudno-magistrates-court'],
  ['Llanelli Law Courts', 'https://www.find-court-tribunal.service.gov.uk/courts/llanelli-law-courts'],
  [
    'London (Central) Social Security and Child Support Tribunal',
    'https://www.find-court-tribunal.service.gov.uk/courts/london-central-social-security-and-child-support-tribunal',
  ],
  [
    'London (South) Employment Tribunal',
    'https://www.find-court-tribunal.service.gov.uk/courts/london-south-employment-tribunal',
  ],
  [
    'London Circuit Commercial Court',
    'https://www.find-court-tribunal.service.gov.uk/courts/london-circuit-commercial-court',
  ],
  ['Loughborough Court', 'https://www.find-court-tribunal.service.gov.uk/courts/loughborough-court'],
  [
    "Luton and South Bedfordshire Magistrates' Court",
    'https://www.find-court-tribunal.service.gov.uk/courts/luton-and-south-bedfordshire-magistrates-court',
  ],
  ['Luton Crown Court', 'https://www.find-court-tribunal.service.gov.uk/courts/luton-crown-court'],
  [
    'Maidstone Combined Court Centre',
    'https://www.find-court-tribunal.service.gov.uk/courts/maidstone-combined-court-centre',
  ],
  ["Maidstone Magistrates' Court", 'https://www.find-court-tribunal.service.gov.uk/courts/maidstone-magistrates-court'],
  [
    'Manchester Civil Justice Centre (Civil and Family Courts)',
    'https://www.find-court-tribunal.service.gov.uk/courts/manchester-civil-justice-centre-civil-and-family-courts',
  ],
  [
    'Manchester Crown Court (Crown Square)',
    'https://www.find-court-tribunal.service.gov.uk/courts/manchester-crown-court-crown-square',
  ],
  [
    'Manchester Crown Court (Minshull St)',
    'https://www.find-court-tribunal.service.gov.uk/courts/manchester-crown-court-minshull-st',
  ],
  [
    "Manchester Magistrates' Court",
    'https://www.find-court-tribunal.service.gov.uk/courts/manchester-magistrates-court',
  ],
  [
    "Mansfield Magistrates' and County Court",
    'https://www.find-court-tribunal.service.gov.uk/courts/mansfield-magistrates-and-county-court',
  ],
  ["Margate Magistrates' Court", 'https://www.find-court-tribunal.service.gov.uk/courts/margate-magistrates-court'],
  [
    "Mayor's and City of London Court",
    'https://www.find-court-tribunal.service.gov.uk/courts/mayors-and-city-of-london-court',
  ],
  [
    'Medway (Chatham) Magistrates Court and Family Court',
    'https://www.find-court-tribunal.service.gov.uk/courts/medway-chatham-magistrates-court-and-family-court',
  ],
  [
    'Medway County Court and Family Court',
    'https://www.find-court-tribunal.service.gov.uk/courts/medway-county-court-and-family-court',
  ],
  [
    'Merthyr Tydfil Combined Court Centre',
    'https://www.find-court-tribunal.service.gov.uk/courts/merthyr-tydfil-combined-court-centre',
  ],
  [
    'Mid and South East Northumberland Law Courts',
    'https://www.find-court-tribunal.service.gov.uk/courts/mid-and-south-east-northumberland-law-courts',
  ],
  [
    'Middlesbrough County Court at Teesside Combined Court',
    'https://www.find-court-tribunal.service.gov.uk/courts/middlesbrough-county-court-at-teesside-combined-court',
  ],
  [
    'Milton Keynes County Court and Family Court',
    'https://www.find-court-tribunal.service.gov.uk/courts/milton-keynes-county-court-and-family-court',
  ],
  [
    "Milton Keynes Magistrates' Court and Family Court",
    'https://www.find-court-tribunal.service.gov.uk/courts/milton-keynes-magistrates-court-and-family-court',
  ],
  ['Mold Justice Centre', 'https://www.find-court-tribunal.service.gov.uk/courts/mold-justice-centre'],
  [
    'Newcastle Civil & Family Courts and Tribunals Centre',
    'https://www.find-court-tribunal.service.gov.uk/courts/newcastle-civil-family-courts-and-tribunals-centre',
  ],
  [
    'Newcastle District Probate Registry',
    'https://www.find-court-tribunal.service.gov.uk/courts/newcastle-district-probate-registry',
  ],
  [
    "Newcastle upon Tyne Crown Court and Magistrates' Court",
    'https://www.find-court-tribunal.service.gov.uk/courts/newcastle-upon-tyne-combined-court-centre',
  ],
  [
    'Newport (South Wales) County Court and Family Court',
    'https://www.find-court-tribunal.service.gov.uk/courts/newport-south-wales-county-court-and-family-court',
  ],
  [
    'Newport (South Wales) Crown Court',
    'https://www.find-court-tribunal.service.gov.uk/courts/newport-south-wales-crown-court',
  ],
  [
    "Newport (South Wales) Magistrates' Court",
    'https://www.find-court-tribunal.service.gov.uk/courts/newport-south-wales-magistrates-court',
  ],
  [
    "Newton Abbot Magistrates' Court",
    'https://www.find-court-tribunal.service.gov.uk/courts/newton-abbot-magistrates-court',
  ],
  [
    "Newton Aycliffe Magistrates' Court",
    'https://www.find-court-tribunal.service.gov.uk/courts/newton-aycliffe-magistrates-court',
  ],
  [
    'North Shields County Court and Family Court',
    'https://www.find-court-tribunal.service.gov.uk/courts/north-shields-county-court-and-family-court',
  ],
  [
    "North Somerset Magistrates' Court",
    'https://www.find-court-tribunal.service.gov.uk/courts/north-somerset-magistrates-court',
  ],
  [
    'North Staffordshire Justice Centre',
    'https://www.find-court-tribunal.service.gov.uk/courts/north-staffordshire-justice-centre',
  ],
  [
    "North Tyneside Magistrates' Court",
    'https://www.find-court-tribunal.service.gov.uk/courts/north-tyneside-magistrates-court',
  ],
  [
    'Northampton Crown, County and Family Court',
    'https://www.find-court-tribunal.service.gov.uk/courts/northampton-crown-county-and-family-court',
  ],
  [
    "Northampton Magistrates' Court",
    'https://www.find-court-tribunal.service.gov.uk/courts/northampton-magistrates-court',
  ],
  [
    'Norwich Combined Court Centre',
    'https://www.find-court-tribunal.service.gov.uk/courts/norwich-combined-court-centre',
  ],
  [
    "Norwich Magistrates' Court and Family Court",
    'https://www.find-court-tribunal.service.gov.uk/courts/norwich-magistrates-court-and-family-court',
  ],
  [
    'Nottingham County Court and Family Court',
    'https://www.find-court-tribunal.service.gov.uk/courts/nottingham-county-court-and-family-court',
  ],
  ['Nottingham Crown Court', 'https://www.find-court-tribunal.service.gov.uk/courts/nottingham-crown-court'],
  [
    "Nottingham Magistrates' Court",
    'https://www.find-court-tribunal.service.gov.uk/courts/nottingham-magistrates-court',
  ],
  ['Nuneaton County Court', 'https://www.find-court-tribunal.service.gov.uk/courts/nuneaton-county-court'],
  ["Nuneaton Magistrates' Court", 'https://www.find-court-tribunal.service.gov.uk/courts/nuneaton-magistrates-court'],
  [
    'Oxford Combined Court Centre',
    'https://www.find-court-tribunal.service.gov.uk/courts/oxford-combined-court-centre',
  ],
  [
    'Oxford District Probate Registry',
    'https://www.find-court-tribunal.service.gov.uk/courts/oxford-district-probate-registry',
  ],
  ['Oxford Magistrates Court', 'https://www.find-court-tribunal.service.gov.uk/courts/oxford-magistrates-court'],
  ['Patents Court', 'https://www.find-court-tribunal.service.gov.uk/courts/patents-court'],
  [
    'Peterborough Combined Court Centre',
    'https://www.find-court-tribunal.service.gov.uk/courts/peterborough-combined-court-centre',
  ],
  [
    "Peterborough Magistrates' Court",
    'https://www.find-court-tribunal.service.gov.uk/courts/peterborough-magistrates-court',
  ],
  ["Peterlee Magistrates' Court", 'https://www.find-court-tribunal.service.gov.uk/courts/peterlee-magistrates-court'],
  ['Plymouth Combined Court', 'https://www.find-court-tribunal.service.gov.uk/courts/plymouth-combined-court'],
  ["Plymouth Magistrates' Court", 'https://www.find-court-tribunal.service.gov.uk/courts/plymouth-magistrates-court'],
  [
    'Pontypridd County Court and Family Court',
    'https://www.find-court-tribunal.service.gov.uk/courts/pontypridd-county-court-and-family-court',
  ],
  ["Poole Magistrates' Court", 'https://www.find-court-tribunal.service.gov.uk/courts/poole-magistrates-court'],
  [
    'Portsmouth Combined Court Centre',
    'https://www.find-court-tribunal.service.gov.uk/courts/portsmouth-combined-court-centre',
  ],
  [
    "Portsmouth Magistrates' Court",
    'https://www.find-court-tribunal.service.gov.uk/courts/portsmouth-magistrates-court',
  ],
  [
    'Preston Combined Court Centre',
    'https://www.find-court-tribunal.service.gov.uk/courts/preston-combined-court-centre',
  ],
  [
    'Preston Crown Court and Family Court (Sessions House)',
    'https://www.find-court-tribunal.service.gov.uk/courts/preston-crown-court-and-family-court-sessions-house',
  ],
  ["Preston Magistrates' Court", 'https://www.find-court-tribunal.service.gov.uk/courts/preston-magistrates-court'],
  [
    'Reading County Court and Family Court',
    'https://www.find-court-tribunal.service.gov.uk/courts/reading-county-court-and-family-court',
  ],
  ['Reading Crown Court', 'https://www.find-court-tribunal.service.gov.uk/courts/reading-crown-court'],
  [
    "Reading Magistrates' Court and Family Court",
    'https://www.find-court-tribunal.service.gov.uk/courts/reading-magistrates-court-and-family-court',
  ],
  ["Redditch Magistrates' Court", 'https://www.find-court-tribunal.service.gov.uk/courts/redditch-magistrates-court'],
  [
    'Reedley Family Hearing Centre',
    'https://www.find-court-tribunal.service.gov.uk/courts/reedley-family-hearing-centre',
  ],
  [
    'Rolls Building, Business and Property Courts of England & Wales',
    'https://www.find-court-tribunal.service.gov.uk/courts/rolls-building-business-and-property-courts-of-england-wales',
  ],
  [
    'Romford County Court and Family Court',
    'https://www.find-court-tribunal.service.gov.uk/courts/romford-county-court-and-family-court',
  ],
  [
    "Romford Magistrates' Court (formerly Havering Magistrates' Court)",
    'https://www.find-court-tribunal.service.gov.uk/courts/romford-magistrates-court-formerly-havering-magistrates-court',
  ],
  ['Royal Courts of Justice', 'https://www.find-court-tribunal.service.gov.uk/courts/royal-courts-of-justice'],
  ['Salisbury Law Courts', 'https://www.find-court-tribunal.service.gov.uk/courts/salisbury-law-courts'],
  ['Scarborough Justice Centre', 'https://www.find-court-tribunal.service.gov.uk/courts/scarborough-justice-centre'],
  ["Sefton Magistrates' Court", 'https://www.find-court-tribunal.service.gov.uk/courts/sefton-magistrates-court'],
  ['Senior Courts Costs Office', 'https://www.find-court-tribunal.service.gov.uk/courts/senior-courts-costs-office'],
  [
    "Sevenoaks Magistrates' Court and Family Court",
    'https://www.find-court-tribunal.service.gov.uk/courts/sevenoaks-magistrates-court-and-family-court',
  ],
  [
    'Sheffield Combined Court Centre',
    'https://www.find-court-tribunal.service.gov.uk/courts/sheffield-combined-court-centre',
  ],
  [
    'Sheffield Designated Family Court',
    'https://www.find-court-tribunal.service.gov.uk/courts/sheffield-designated-family-court',
  ],
  ["Sheffield Magistrates' Court", 'https://www.find-court-tribunal.service.gov.uk/courts/sheffield-magistrates-court'],
  ['Shrewsbury Crown Court', 'https://www.find-court-tribunal.service.gov.uk/courts/shrewsbury-crown-court'],
  [
    'Skipton County Court and Family Court',
    'https://www.find-court-tribunal.service.gov.uk/courts/skipton-county-court-and-family-court',
  ],
  ["Skipton Magistrates' Court", 'https://www.find-court-tribunal.service.gov.uk/courts/skipton-magistrates-court'],
  [
    'Slough County Court and Family Court',
    'https://www.find-court-tribunal.service.gov.uk/courts/slough-county-court-and-family-court',
  ],
  ['Snaresbrook Crown Court', 'https://www.find-court-tribunal.service.gov.uk/courts/snaresbrook-crown-court'],
  [
    'South Tyneside County Court and Family Court',
    'https://www.find-court-tribunal.service.gov.uk/courts/south-tyneside-county-court-and-family-court',
  ],
  [
    "South Tyneside Magistrates' Court",
    'https://www.find-court-tribunal.service.gov.uk/courts/south-tyneside-magistrates-court',
  ],
  [
    "Southampton (West Hampshire) Magistrates' Court",
    'https://www.find-court-tribunal.service.gov.uk/courts/southampton-west-hampshire-magistrates-court',
  ],
  [
    'Southampton Combined Court Centre',
    'https://www.find-court-tribunal.service.gov.uk/courts/southampton-combined-court-centre',
  ],
  [
    'Southend County Court and Family Court',
    'https://www.find-court-tribunal.service.gov.uk/courts/southend-county-court-and-family-court',
  ],
  ['Southend Crown Court', 'https://www.find-court-tribunal.service.gov.uk/courts/southend-crown-court'],
  ["Southend Magistrates' Court", 'https://www.find-court-tribunal.service.gov.uk/courts/southend-magistrates-court'],
  ['Southwark Crown Court', 'https://www.find-court-tribunal.service.gov.uk/courts/southwark-crown-court'],
  ['St Albans Crown Court', 'https://www.find-court-tribunal.service.gov.uk/courts/st-albans-crown-court'],
  ["St Albans Magistrates' Court", 'https://www.find-court-tribunal.service.gov.uk/courts/st-albans-magistrates-court'],
  [
    'St Helens County Court and Family Court',
    'https://www.find-court-tribunal.service.gov.uk/courts/st-helens-county-court-and-family-court',
  ],
  [
    'Stafford Combined Court Centre',
    'https://www.find-court-tribunal.service.gov.uk/courts/stafford-combined-court-centre',
  ],
  [
    'Staffordshire Central Finance and Enforcement Unit',
    'https://www.find-court-tribunal.service.gov.uk/courts/staffordshire-central-finance-and-enforcement-unit',
  ],
  [
    'Staines County Court and Family Court',
    'https://www.find-court-tribunal.service.gov.uk/courts/staines-county-court-and-family-court',
  ],
  [
    "Staines Magistrates' Court and Family Court",
    'https://www.find-court-tribunal.service.gov.uk/courts/staines-magistrates-court-and-family-court',
  ],
  ["Stevenage Magistrates' Court", 'https://www.find-court-tribunal.service.gov.uk/courts/stevenage-magistrates-court'],
  [
    'Stockport County Court and Family Court',
    'https://www.find-court-tribunal.service.gov.uk/courts/stockport-county-court-and-family-court',
  ],
  ["Stockport Magistrates' Court", 'https://www.find-court-tribunal.service.gov.uk/courts/stockport-magistrates-court'],
  [
    'Stoke-on-Trent Combined Court',
    'https://www.find-court-tribunal.service.gov.uk/courts/stoke-on-trent-combined-court',
  ],
  ["Stratford Magistrates' Court", 'https://www.find-court-tribunal.service.gov.uk/courts/stratford-magistrates-court'],
  [
    'Sunderland County, Family, Magistrates’ and Tribunal Hearings',
    'https://www.find-court-tribunal.service.gov.uk/courts/sunderland-county-family-magistrates-and-tribunal-hearings',
  ],
  ['Swansea Crown Court', 'https://www.find-court-tribunal.service.gov.uk/courts/swansea-crown-court'],
  ["Swansea Magistrates' Court", 'https://www.find-court-tribunal.service.gov.uk/courts/swansea-magistrates-court'],
  ['Swindon Combined Court', 'https://www.find-court-tribunal.service.gov.uk/courts/swindon-combined-court'],
  ["Swindon Magistrates' Court", 'https://www.find-court-tribunal.service.gov.uk/courts/swindon-magistrates-court'],
  ["Tameside Magistrates' Court", 'https://www.find-court-tribunal.service.gov.uk/courts/tameside-magistrates-court'],
  [
    'Taunton Crown, County and Family Court',
    'https://www.find-court-tribunal.service.gov.uk/courts/taunton-crown-county-and-family-court',
  ],
  [
    "Taunton Magistrates' Court, Tribunals and Family Hearing Centre",
    'https://www.find-court-tribunal.service.gov.uk/courts/taunton-magistrates-court-tribunals-and-family-hearing-centre',
  ],
  [
    'Technology & Construction Court',
    'https://www.find-court-tribunal.service.gov.uk/courts/technology-construction-court',
  ],
  [
    'Teesside Combined Court Centre',
    'https://www.find-court-tribunal.service.gov.uk/courts/teesside-combined-court-centre',
  ],
  ["Teesside Magistrates' Court", 'https://www.find-court-tribunal.service.gov.uk/courts/teesside-magistrates-court'],
  [
    'Telford County Court and Family Court',
    'https://www.find-court-tribunal.service.gov.uk/courts/telford-county-court-and-family-court',
  ],
  ["Telford Magistrates' Court", 'https://www.find-court-tribunal.service.gov.uk/courts/telford-magistrates-court'],
  ["Thames Magistrates' Court", 'https://www.find-court-tribunal.service.gov.uk/courts/thames-magistrates-court'],
  [
    'Thanet County Court and Family Court',
    'https://www.find-court-tribunal.service.gov.uk/courts/thanet-county-court-and-family-court',
  ],
  [
    'Torquay and Newton Abbot County and Family Court',
    'https://www.find-court-tribunal.service.gov.uk/courts/torquay-and-newton-abbot-county-court-and-family-court',
  ],
  ['Truro Combined Court', 'https://www.find-court-tribunal.service.gov.uk/courts/truro-county-court-and-family-court'],
  ["Truro Magistrates' Court", 'https://www.find-court-tribunal.service.gov.uk/courts/truro-magistrates-court'],
  [
    'Uxbridge County Court and Family Court',
    'https://www.find-court-tribunal.service.gov.uk/courts/uxbridge-county-court-and-family-court',
  ],
  ["Uxbridge Magistrates' Court", 'https://www.find-court-tribunal.service.gov.uk/courts/uxbridge-magistrates-court'],
  ['Wales Employment Tribunal', 'https://www.find-court-tribunal.service.gov.uk/courts/wales-employment-tribunal'],
  [
    'Walsall County and Family Court',
    'https://www.find-court-tribunal.service.gov.uk/courts/walsall-county-and-family-court',
  ],
  ["Walsall Magistrates' Court", 'https://www.find-court-tribunal.service.gov.uk/courts/walsall-magistrates-court'],
  [
    'Wandsworth County Court and Family Court',
    'https://www.find-court-tribunal.service.gov.uk/courts/wandsworth-county-court-and-family-court',
  ],
  [
    'War Pensions & Armed Forces Compensation Chamber',
    'https://www.find-court-tribunal.service.gov.uk/courts/war-pensions-armed-forces-compensation-chamber',
  ],
  ['Warrington Crown Court', 'https://www.find-court-tribunal.service.gov.uk/courts/warrington-crown-court'],
  [
    "Warrington Magistrates' Court",
    'https://www.find-court-tribunal.service.gov.uk/courts/warrington-magistrates-court',
  ],
  ['Warwick Combined Court', 'https://www.find-court-tribunal.service.gov.uk/courts/warwick-combined-court'],
  [
    'Watford County Court and Family Court',
    'https://www.find-court-tribunal.service.gov.uk/courts/watford-county-court-and-family-court',
  ],
  [
    "Wellingborough Magistrates' Court",
    'https://www.find-court-tribunal.service.gov.uk/courts/wellingborough-magistrates-court',
  ],
  ["Welshpool Magistrates' Court", 'https://www.find-court-tribunal.service.gov.uk/courts/welshpool-magistrates-court'],
  ['West Cumbria Courthouse', 'https://www.find-court-tribunal.service.gov.uk/courts/west-cumbria-courthouse'],
  ['West London Family Court', 'https://www.find-court-tribunal.service.gov.uk/courts/west-london-family-court'],
  [
    "Westminster Magistrates' Court",
    'https://www.find-court-tribunal.service.gov.uk/courts/westminster-magistrates-court',
  ],
  [
    'Weston-Super-Mare County Court and Family Court',
    'https://www.find-court-tribunal.service.gov.uk/courts/weston-super-mare-county-court-and-family-court',
  ],
  ['Weymouth Combined Court', 'https://www.find-court-tribunal.service.gov.uk/courts/weymouth-combined-court'],
  [
    "Wigan and Leigh Magistrates' Court",
    'https://www.find-court-tribunal.service.gov.uk/courts/wigan-and-leigh-magistrates-court',
  ],
  [
    'Wigan County Court and Family Court',
    'https://www.find-court-tribunal.service.gov.uk/courts/wigan-county-court-and-family-court',
  ],
  [
    'Willesden County Court and Family Court',
    'https://www.find-court-tribunal.service.gov.uk/courts/willesden-county-court-and-family-court',
  ],
  ["Willesden Magistrates' Court", 'https://www.find-court-tribunal.service.gov.uk/courts/willesden-magistrates-court'],
  ["Wimbledon Magistrates' Court", 'https://www.find-court-tribunal.service.gov.uk/courts/wimbledon-magistrates-court'],
  [
    'Winchester Combined Court Centre',
    'https://www.find-court-tribunal.service.gov.uk/courts/winchester-combined-court-centre',
  ],
  [
    'Winchester District Probate Registry',
    'https://www.find-court-tribunal.service.gov.uk/courts/winchester-district-probate-registry',
  ],
  ["Wirral Magistrates' Court", 'https://www.find-court-tribunal.service.gov.uk/courts/wirral-magistrates-court'],
  [
    'Wolverhampton Combined Court Centre',
    'https://www.find-court-tribunal.service.gov.uk/courts/wolverhampton-combined-court-centre',
  ],
  [
    "Wolverhampton Magistrates' Court",
    'https://www.find-court-tribunal.service.gov.uk/courts/wolverhampton-magistrates-court',
  ],
  ['Wood Green Crown Court', 'https://www.find-court-tribunal.service.gov.uk/courts/wood-green-crown-court'],
  ['Woolwich Crown Court', 'https://www.find-court-tribunal.service.gov.uk/courts/woolwich-crown-court'],
  ['Worcester Combined Court', 'https://www.find-court-tribunal.service.gov.uk/courts/worcester-combined-court'],
  [
    'Worthing County Court and Family Court',
    'https://www.find-court-tribunal.service.gov.uk/courts/worthing-county-court-and-family-court',
  ],
  ["Worthing Magistrates' Court", 'https://www.find-court-tribunal.service.gov.uk/courts/worthing-magistrates-court'],
  [
    'Wrexham County and Family Court',
    'https://www.find-court-tribunal.service.gov.uk/courts/wrexham-county-and-family--court',
  ],
  ["Wrexham Magistrates' Court", 'https://www.find-court-tribunal.service.gov.uk/courts/wrexham-magistrates-court'],
  [
    "Yeovil County, Family and Magistrates' Court",
    'https://www.find-court-tribunal.service.gov.uk/courts/yeovil-county-family-and-magistrates-court',
  ],
  [
    'York County Court and Family Court',
    'https://www.find-court-tribunal.service.gov.uk/courts/york-county-court-and-family-court',
  ],
  ['York Crown Court', 'https://www.find-court-tribunal.service.gov.uk/courts/york-crown-court'],
  [
    "York Magistrates' Court and Family Court",
    'https://www.find-court-tribunal.service.gov.uk/courts/york-magistrates-court-and-family-court',
  ],
  [
    'Chelmsford Justice Centre',
    'https://www.find-court-tribunal.service.gov.uk/courts/chelmsford-county-and-family-court',
  ],
  ['Chesterfield Justice Centre', 'https://www.find-court-tribunal.service.gov.uk/courts/chesterfield-justice-centre'],
  ['Harrogate Justice Centre', 'https://www.find-court-tribunal.service.gov.uk/courts/harrogate-justice-centre'],
  ['Luton Justice Centre', 'https://www.find-court-tribunal.service.gov.uk/courts/luton-justice-centre'],
  ['Aberystwyth Justice Centre', 'https://www.find-court-tribunal.service.gov.uk/courts/aberystwyth-justice-centre'],
  ['Aldershot Justice Centre', 'https://www.find-court-tribunal.service.gov.uk/courts/aldershot-justice-centre'],
  [
    'Birmingham Civil and Family Justice Centre',
    'https://www.find-court-tribunal.service.gov.uk/courts/birmingham-civil-and-family-justice-centre',
  ],
  [
    'Bristol Civil and Family Justice Centre',
    'https://www.find-court-tribunal.service.gov.uk/courts/bristol-civil-and-family-justice-centre',
  ],
  ['Caernarfon Justice Centre', 'https://www.find-court-tribunal.service.gov.uk/courts/caernarfon-justice-centre'],
  [
    'Cardiff Civil and Family Justice Centre',
    'https://www.find-court-tribunal.service.gov.uk/courts/cardiff-civil-and-family-justice-centre',
  ],
  [
    'Chester Civil and Family Justice Centre',
    'https://www.find-court-tribunal.service.gov.uk/courts/chester-civil-and-family-justice-centre',
  ],
  [
    'Doncaster Justice Centre North',
    'https://www.find-court-tribunal.service.gov.uk/courts/doncaster-justice-centre-north',
  ],
  [
    'Doncaster Justice Centre South',
    'https://www.find-court-tribunal.service.gov.uk/courts/doncaster-justice-centre-south',
  ],
  ['Havant Justice Centre', 'https://www.find-court-tribunal.service.gov.uk/courts/havant-justice-centre'],
  ['Hereford Justice Centre', 'https://www.find-court-tribunal.service.gov.uk/courts/hereford-justice-centre'],
  ['Mold Justice Centre', 'https://www.find-court-tribunal.service.gov.uk/courts/mold-justice-centre'],
  [
    'North Staffordshire Justice Centre',
    'https://www.find-court-tribunal.service.gov.uk/courts/north-staffordshire-justice-centre',
  ],
  ['Port Talbot Justice Centre', 'https://www.find-court-tribunal.service.gov.uk/courts/port-talbot-justice-centre'],
  ['Prestatyn Justice Centre', 'https://www.find-court-tribunal.service.gov.uk/courts/prestatyn-justice-centre'],
  ['Scarborough Justice Centre', 'https://www.find-court-tribunal.service.gov.uk/courts/scarborough-justice-centre'],
  [
    'Single Justice Procedures Service Centre',
    'https://www.find-court-tribunal.service.gov.uk/courts/single-justice-procedures-service-centre',
  ],
  [
    'Swansea Civil Justice Centre',
    'https://www.find-court-tribunal.service.gov.uk/courts/swansea-civil-justice-centre',
  ],
  [
    'Wakefield Civil and Family Justice Centre',
    'https://www.find-court-tribunal.service.gov.uk/courts/wakefield-civil-and-family-justice-centre',
  ],
  ['Worcester Justice Centre', 'https://www.find-court-tribunal.service.gov.uk/courts/worcester-justice-centre'],
  [
    'Derby Social Security and Child Support Tribunal',
    'https://www.find-court-tribunal.service.gov.uk/courts/derby-social-security-and-child-support-tribunal',
  ],
  ['Family Division', 'https://www.find-court-tribunal.service.gov.uk/courts/family-division'],
  [
    'Inverness Employment Tribunal',
    'https://www.find-court-tribunal.service.gov.uk/courts/inverness-employment-tribunal',
  ],
  [
    'Inverness Social Security and Child Support Tribunal',
    'https://www.find-court-tribunal.service.gov.uk/courts/inverness-social-security-and-child-support-tribunal',
  ],
  ["King's Bench Division", 'https://www.find-court-tribunal.service.gov.uk/courts/kings-bench-division'],
  [
    'Midlands (East)Employment Tribunal',
    'https://www.find-court-tribunal.service.gov.uk/courts/midlands-eastemployment-tribunal',
  ],
])

export default {
  getCourtsMap: () => courtsMap,
  getAllCourts: () => allCourts,
  getCourtsNameMapping: () => courtsNameMapping,
  getCourtUrl,
}
